@echo off
echo Change to project root...
cd ../../../../
echo Push to repo...
git push
echo Sending commands to test server...
echo sh ./project_root/migration.sh ; exit | plink root@127.0.0.1 -P 22 -pw MyPassword
echo Operation was successful.
